openapi: 3.0.0
info:
  title: Tshirt store API
  description: This for learning create API for ecommerce store
  version: 1.1.0
  contact:
    email: fjmoradiya@gmail.com
    url: "https://devfenil.hashnode.dev/"

# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing

servers:
  - url: "{protocol}://localhost:1353/api/{version}"
    description: Local Server - regular
    variables:
      version:
        default: v1
        enum:
          - v1
          - v2
      protocol:
        default: http
        enum:
          - http
          - https

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: return a greet message from /codex
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: All Client Bad request
        500:
          description: All Server Bad responses
